book/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BookListView.as_view(), name='book_list'),

    path('book_list_delete/', views.BookListDeleteView.as_view(), name='book_list_delete'),
    path('book_list/<int:id>/delete/', views.BookDropDeleteView.as_view()),
    path('book_list_edit/', views.BookUpdateListView.as_view(), name='book_list_edit'),
    path('book_list/<int:id>/update/', views.BookEditView.as_view()),
    path('search/', views.SearchView.as_view(), name='search'),


    path('book_list/<int:id>/', views.BookDetailView.as_view(), name='book_detail'),
    path('create_book/', views.BookCreateView.as_view(), name='add_books'),

    path('about_me/', views.about_view),
    path('my_friend/', views.my_friend_view),
    path('datetime/', views.datetime_view),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
    path('', include('product.urls')),
    path('', include('users.urls')),
    path('', include('parser.urls')),
    path('', include('tv_show.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

tv_show/models.py
from django.db import models

# Создание новой таблицы с названием Movie
class Movie(models.Model):

    GENRE_CHOICES = (
        ('Ужасы', 'Ужасы'),
        ('Комедия', 'Комедия'),
        ('Фантастика', 'Фантастика')
    )

    title = models.CharField(max_length=255,
                             verbose_name='enter title', db_index=True, null=True)
    image = models.ImageField(upload_to='tv_show/', db_index=True, null=True)
    description = models.TextField(verbose_name='write description', db_index=True, null=True)
    genre = models.CharField(max_length=100, choices=GENRE_CHOICES, db_index=True, null=True)
    price = models.PositiveIntegerField(verbose_name='write price', db_index=True, null=True)
    # Если вы после миграций забыли указать какое-то поле, то так же создаете его,
    # но в атрибуте нового поля, указываете null=True и заново проводите миграции (PS: даже если вы изменили название поля)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, null=True)


    def __str__(self):
        return f'{self.title} - {self.created_at}'

class ReviewMovie(models.Model):
    movie_review = models.ForeignKey(Movie, on_delete=models.CASCADE, related_name='review_movie', db_index=True, null=True)
    text_movie = models.TextField(db_index=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, null=True)

    def __str__(self):
        return f'{self.text_movie} - {self.created_at}'

templates/crud/book_list_delete.html
{% include '../header.html' %}
<br><br><br>

<center>
<div class="square_mom">
{% for i in book_object %}
<div class="card mb-3" style="max-width: 540px; justify-content: center">
  <div class="row g-0">
    <div class="col-md-4">
     </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <a href="/book_list/{{i.id }}/delete/" class="btn btn-primary">Удалить</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

</div>
</center>

{% include '../footer.html' %}

templates/crud/book_list_edit.html
{% include '../header.html' %}
<br><br><br>

<center>
<div class="square_mom">
{% for i in book_object %}
<div class="card mb-3" style="max-width: 540px; justify-content: center">
  <div class="row g-0">
    <div class="col-md-4">
     </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <a href="/book_list/{{ i.id }}/update/" class="btn btn-primary">Выбрать для редактирования</a>
      </div>
      </div>
  </div>
</div>
{% endfor %}

</div>
</center>

{% include '../footer.html' %}

templates/crud/confirm_delete.html
{% load static %}
{% include '../header.html' %}

<br><br><br>

<form method="POST" enctype="multipart/form-data">
    <h1>Вы уверенны, что хотите удалить этот объект?</h1>
    {% csrf_token %}
    <button type="submit">ДА</button>
    <button><a href="{% url 'book_list_delete' %}">Назад</a></button>
</form>

{% include '../footer.html' %}

templates/crud/confirm_movie_delete.html
{% load static %}
{% include '../header.html' %}

<br><br><br>

<form method="POST" enctype="multipart/form-data">
    <h1>Вы уверены, что хотите удалить этот фильм?</h1>
    {% csrf_token %}
    <button type="submit">ДА</button>
    <button><a href="{% url 'book_list_delete' %}">Назад</a></button>
</form>

{% include '../footer.html' %}

templates/crud/create_book.html
{% load static %}
{% include '../header.html' %}
<link rel="stylesheet" href="{% static 'css/create_form.css'%}">
<br><br><br>


<center>
<form action ="/create_book/" method = "POST" enctype="multipart/form-data" class="decor">
<div class="form-left-decoration"></div>
<div class="form-right-decoration"></div>
<div class="circle"></div>
<div class="form-inner">
<h3>Добавить книгу</h3>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" >Добавить книгу</button>
</div>
</form>
</center>

{% include '../footer.html' %}

templates/crud/create_movie.html
{% load static %}
{% include '../header.html' %}
<link rel="stylesheet" href="{% static 'css/create_form.css'%}">
<br><br><br>


<center>
<form action ="/create_movie/" method = "POST" enctype="multipart/form-data" class="decor">
<div class="form-left-decoration"></div>
<div class="form-right-decoration"></div>
<div class="circle"></div>
<div class="form-inner">
<h3>Добавить фильм</h3>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" >Добавить фильм</button>
</div>
</form>
</center>

{% include '../footer.html' %}

templates/crud/movie_list_delete.html
{% include '../header.html' %}
<br><br><br>

<center>
<div class="square_mom">
{% for i in book_object %}
<div class="card mb-3" style="max-width: 540px; justify-content: center">
  <div class="row g-0">
    <div class="col-md-4">
     </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <a href="/movie_list/{{i.id }}/delete/" class="btn btn-primary">Удалить фильм</a>
      </div>
    </div>
  </div>
</div>
{% endfor %}

</div>
</center>

{% include '../footer.html' %}

templates/crud/movie_list_edit.html
{% include '../header.html' %}
<br><br><br>

<center>
<div class="square_mom">
{% for i in movie_object %}
<div class="card mb-3" style="max-width: 540px; justify-content: center">
  <div class="row g-0">
    <div class="col-md-4">
     </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ i.title }}</h5>
        <a href="/movie_list/{{ i.id }}/update/" class="btn btn-primary">Выбрать фильм для редактирования</a>
      </div>
      </div>
  </div>
</div>
{% endfor %}

</div>
</center>

{% include '../footer.html' %}

templates/crud/update_book.html
{% load static %}
{% include '../header.html' %}
<br><br><br>
<link rel="stylesheet" href="{% static 'css/update_form.css'%}">


<form method = "POST" enctype="multipart/from-data" class="transparent">
    <div class="form-inner">
        <h3>Изменить</h3>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Отправить">
    </div>
</form>

{% include '../footer.html' %}

templates/crud/update_movie.html
{% load static %}
{% include '../header.html' %}
<br><br><br>
<link rel="stylesheet" href="{% static 'css/update_form.css'%}">


<form method = "POST" enctype="multipart/from-data" class="transparent">
    <div class="form-inner">
        <h3>Изменить фильм</h3>
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Отправить">
    </div>
</form>

{% include '../footer.html' %}